= The DCAT-AP book
:author: Bart Hanssens
:email: <bart.hanssens@bosa.fgov.be>
:url-repo: https://github.com/Fedict/dcatbook/
:revdate: 2024-06-13
:source-highlighter: roug
:license-url: https://creativecommons.org/public-domain/cc0/
:license-title: CC0
:docinfo: shared
:doctype: docbook
:toc: left

== About the author

Bart Hanssens is the architect of the Belgian data portal data.gov.be.
While the front-end of this portal may not be the most attractive site in existence,
the back-end was designed to work with DCAT-AP since 2014,
collecting and harmonizing metadata from various local, regional and federal sources.

Bart contributed to the DCAT-AP specification, and the open source linked data library Eclipse RDF4J.


= Introduction to linked data

== Problem statement 

So to sum up, we want

* unique, easy to generate identifiers
* easy to find documentation


== Introduction to linked data

Resource Description Framework

=== Statements and triples ===

RDF is about making _statements_, which are basic sentences to describe something.
written down as a combination 3 parts (hence the name _triples_).

`<subject> <predicate> <object>`


=== Unique identifiers

One way to make sure identifiers are unique, is to use a common database or registration system.

Luckily there is a decentralized solution, based on domain names.

===

URN, URI, IRI

==== URI and URLs


[NOTE]
====
`http://example.com` and `https://example.com` (note the `s`) are *not* the same identifier.
====

==== Dereferencable URLs

Dereferencable is a fancy word to say that a URL will actually return something meaningful when a browser 
or another tool wants to check it out.

[NOTE]
====
A URL does not _have_ to be dereferencable in order to be used as an identifier, but it helps.
====

==== Persistent URLs (PURL)

A persistent URL (or PURL in short) is nothing more (and nothing less) than an URL that does not change.
For how long ? Basically forever... once a PURL has been created, it is supposed to remain available and 
unchanged until the dawn of time.

=== Beyond three ...


Turns out there is a shortcut: literal values can take a language tag _or_ a datatype, but not both.

It also doesn't work that way for resources

=== File formats

RDF data can be _serialized_ to several file formats

This may come in handy when dealing with 



==== N-Triples

This is a very simple text format, with every line containing one unabbreviated statement.
It can easily be streamed, and works quite nice with well-know command-line tools like `grep` and `awk`.

The downside is that N-Triples files are quite verbose,
since the format does not allow the use of prefixes to abbreviate commonly used namespaces,
nor does it provide options to group or structure statements in a visually appealing way ("pretty-printing").

==== Turtle

Turtle is slightly more complicated, but is much more compact and easier to read.
Prefixes can be used, and some syntactic sugar is available to produce smaller and better looking files.
It is therefore often used for files that are likely to be viewed by subject experts, e.g. data models and thesauri.

==== RDF/XML

RDF/XML was one of the first serialization formats, which is not

The format is quite generic, which means that - even for small amounts of data - 
there are multiple ways to express the 

As with general XML, whitespace and indentation does not matter

==== JSON-LD

=== Embedding in webpages

==== RDFa

It is, however, becoming a less popular solution.

==== JSON-LD in HTML

Search engines like Google benefit from structured data, and can use some 

See https://developers.google.com/search/docs/appearance/structured-data/dataset

== Modelling

=== Classes and properties



=== RDFS

RDF Schema is 

=== OWL

Web Ontology Language (OWL) is much more complex

Yes, the abbreviation should have been `WOL`, but `OWL` sounds better 

=== Reasoning

If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.

== Validating

=== SHACL

Validation is relative new


= Data Catalog (DCAT)

== DCAT

Is a very simple, based on <<DCTERMS>>

=== DCAT 2

DCAT version 2 adds better support for (web)services

=== DCAT 3

DCAT version 3 focusses on documenting series of related datasets.

It is up to decide to the publishere of the datasets 


== DCAT-AP

See also https://semiceu.github.io/DCAT-AP/releases/3.0.0/


=== Catalog

==== Describing the catalog



=== Dataset

==== Describing the dataset

`dct:title`

`dct:description`

`dcat:keyword`
`dcat:theme`

==== Licenses and rights


=== Distribution

==== Accessing and downloading

`dcat:accessURL`
`dcat:downloadURL`

=== Dataservice



== Various specializations

=== BRegDCAT-AP


See also https://github.com/SEMICeu/BregDCAT-AP

=== CiteDCAT-AP

See also https://ec-jrc.github.io/datacite-to-dcat-ap/

=== DCAT-AP-JRC

See also https://ec-jrc.github.io/dcat-ap-jrc/

=== DCAT-AP HvD
Implementing Regulation 2023/138/EU of 21 December 2022 laying down a list of specific high-value datasets and the arrangements for their publication and re-use

See also https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/

=== EPOS-DCAT-AP

See also https://epos-eu.github.io/EPOS-DCAT-AP/

=== GeoDCAT-AP
Directive 2007/2/EC of 14 March 2007 establishing an Infrastructure for Spatial Information in the European Community (INSPIRE)

https://semiceu.github.io/GeoDCAT-AP/releases/

=== GNSS-DCAT-AP

See also https://zenodo.org/records/10955559

=== HealthDCAT-AP

See also https://healthdcat-ap.github.io/

=== MLDCAT-AP

See also https://semiceu.github.io/MLDCAT-AP/releases/2.0.0/

=== MobilityDCAT-AP
Directive 2010/40/EU of 7 July 2010 on the framework for the deployment of 
Intelligent Transport Systems in the field of road transport and for interfaces with other modes of transport (ITS)

See also https://w3id.org/mobilitydcat-ap/releases/

=== StatDCAT-AP

See also https://github.com/SEMICeu/StatDCAT-AP

== National variants

=== Belgium
DCAT-AP-BE
DCAT-AP-VL

=== Finland
https://www.avoindata.fi/en/dcat-ap

=== Germany
DCAT-AP.DE

=== Italy: DCAT-AP_IT
https://www.dati.gov.it/content/dcat-ap-it-v10-profilo-italiano-dcat-ap-0

=== The Netherlands: DCAT-AP-DONL
https://dataoverheid.github.io/dcat-ap-donl/

=== Norway: DCAT-AP-NO
https://data.norge.no/specification/dcat-ap-no

=== Poland: DCAT-AP-PL
https://dane.gov.pl/dcat-ap-pl/

=== Spain: DCAT-AP-Spain

=== Sweden: DCAT-AP-SE
https://docs.dataportal.se/dcat/en/

=== Switserland: DCAT-AP CH
https://www.dcat-ap.ch/

= Vocabularies

== ADMS

== DCTERMS

[cols="1h,1"]
|===
|Full name | Dublin Core Metadata Initiative Terms
|See also | https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
|===


Most people will associate Dublin with the capital of Ireland, 
but in this case it refers to Dublin in Ohio, USA.

== DQV

[cols="1h,1"]
|===
|Full name | Data Quality Vocabulary
|See also | https://www.w3.org/TR/vocab-dqv/
|===



== FOAF

[cols="1h,1"]
|===
|Full name | Friend-of-a-Friend
|See also | http://xmlns.com/foaf/spec/
|===

== LOCN

== ORG



== ROV

== Schema.org

== SKOS

It is very well suited to publish code lists and 

A _term_ (entry in a thesauri) 
`skos:Concept`

The `skos:broader` (and the inverse property `skos:narrower`) is used to create hierachical structures.

=== Labels

Every term should have a preferred label `skos:prefLabel` (possibly in multiple languages), 
and may have multiple alternative labels `skos:altLabel` 

In addition - or instead of a - prefLabel

=== Mapping to other thesauri

It is also possible to compare terms in one thesaurus with terms belonging to another thesaurus,
using the `skos:broadMatch`, `skos:narrowMatch`, `skos:closeMatch` and `skos:exactMatch` properties.


The EU Publications Office publishes various code lists and thesauri in SKOS,
ranging from simple lists like the https://op.europa.eu/en/web/eu-vocabularies/authority-tables[Authority tables]
to massive thesauri like https://op.europa.eu/en/web/eu-vocabularies/thesauri[EUROVOC]

See also https://www.w3.org/TR/skos-primer/

== VCARD

See also https://www.w3.org/TR/vcard-rdf/

== XSD



[appendix]
= Common mistakes in DCAT-AP


== Not using the EU Publications Office controlled lists

Some portals claim to adhere to DCAT-AP, but are in fact producing DCAT.

== Incorrect date or duration formats


== Mixing IDs and URLs

This can lead to undesired side-effects when quering / combining data.


== Not setting explicit language tags


= Tools

== 

To find the preferred prefix and/or namespaces: https://prefix.cc/

==


=== 


.DRAFT
----
This document is only a rough draft.
----
