= The DCAT-AP book: Everything you never wanted to know about data catalogs, but had to learn anyway
:author: Bart Hanssens
:email: <bart.hanssens@bosa.fgov.be>
:url-repo: https://github.com/Fedict/dcatbook/
:revdate: 2024-06-13
:source-highlighter: roug
:license-url: https://creativecommons.org/public-domain/cc0/
:license-title: CC0
:docinfo: shared
:doctype: docbook
:toc: left

.DRAFT
----
This document is only a rough draft.
----

[preface]
= Preamble

=== About this book
 
The intention is not to be an exhaustive reference of each and every detail,
but to be a practical guide for developers of data portals and other interested parties.

=== About the author

Bart Hanssens is the architect of the Belgian data portal data.gov.be.
While the front-end of this portal may not be the most attractive site in existence,
the back-end was designed to work with DCAT-AP since 2014,
collecting and harmonizing metadata from various local, regional and federal sources.

Bart contributed to the DCAT-AP specification, and the open source linked data library Eclipse RDF4J.

= Introduction to linked data

== Problem statement 

So to sum up, we want

* unique, easy to generate identifiers
* easy to find documentation


== Introduction to linked data

Resource Description Framework

=== Statements and triples ===

RDF is about making _statements_, which are very basic sentences to describe something,
written down as a combination of exactly 3 parts (hence the name _triples_):

`<subject> <predicate> <object>`

.Example of statements
====
....
<John> <buys an> <apple>
<Jane> <is born in> <Paris>
....
====

Less is more...

So by design it is possible to express _everything_, albeit not necessarily in the most concise way.
For example, it requires multiple statements to express a sentence like 
`John has been working for ACME Corp since September 2015`

Something like:
....
<John> <is an employee in> <Contract>
<ACME Corp> <is an employer in> <Contract>
<Contract> <starts in> "9/2015"
....

This also shows that statements can be linked, or more formally, 
the `object` of one statement can be the `subject` of other statements and vice versa.

=== Unique identifiers

One way to make sure identifiers are unique, is to use a common database or registration system.

Luckily there is a decentralized solution, based on domain names.

=== URN, URI, IRI

==== URI and URLs

[NOTE]
====
With the exception of the `example.com` domain for documentation purposes, 
it is considered bad practice to "create" URIs in someone elses domain.
====

[NOTE]
====
`http://example.com` and `https://example.com` (note the `s`) are *not* the same identifier.
====

==== Dereferencable URIs

Dereferencable is a fancy way to say that a URI will actually return something meaningful when a browser 
or another tool accesses it.

In most cases, this is via a  HTTP GET request. Using the good old HTTP `Accept` header, 
it is possible to 

[NOTE]
====
A URI does not _have_ to be dereferencable in order to be useful, but it helps.
====


==== Persistent URLs (PURL)

A persistent URL (or PURL in short) is nothing more (and nothing less) than an URL that does not change.
For how long ? Basically forever... once a PURL has been created, it is supposed to remain available and 
unchanged until the dawn of time.

=== Literals

Not everything has to be an identifier, often a simple value or _literal_ will do just fine:
book titles, timestamps, house numbers... are just a few random examples.

==== Language tags and data types

Now, a very common use case for titles and descriptions is to have translations,
or at least an indication of the language.


Turns out there is a shortcut: literal values can take a language tag _or_ a datatype (not both).


=== ... and beyond that

In a _graph_ or sometimes called a _context_ 

And more recently, RDF* (RDF-Star)


== Modelling

=== Classes and properties

Classes are 
For instance, a `Document`, a `Person`...

Classes may be subclasses of other (parent) classes

Properties
Properties may be subproperties of other (parent) properties.

Both class names and property names are case-sensitive.
By convention, class name start with an uppercase and property names with a lowercase.

[NOTE]
====
Note that properties are often not tightly coupled to classes,
allowing them to be reused across completely different classes.
====

=== Vocabularies and ontologies

A _vocabulary_ is a well-defined collection of classes and properties.

An _ontology_ is a vocabulary on steroids: not only does it contain definitions,
it also adds some logic constraints.
For instance, an ontology may not allow that something is both a `Document` and an `Organization` at the same time.

=== Reusing vocabularies

Vocabularies can be mixed and matched.
In fact, it's even a best practice to reuse existing ones when developping new vocabularies:
doing so reduces the learning curve for third parties
and increases interoperability between different data sources.

A great vocabularies are already available is the
https://lov.linkeddata.es/[Linked Open Vocabularies] portal

Vocabularies specifically produced by / for administrations of the EU can be found on 
https://joinup.ec.europa.eu/collection/semic-support-centre[SEMIC]

=== RDFS

RDF Schema is 

Domain:

Multiple domains are allowed.

Some properties are indeed very generic, e.g. a `name` property makes sense on a `Person` class,
but can be used on `Organizations` and `Images` as well.


[NOTE]
====
Unlike object-oriented programming, a property doesn't really belong to a specific class.

Which also means it's not a good idea to use the class name as part of the property name, 
e.g. `MyClass_Property`
====

Range:

The class a range points to, does not have to be part of the same vocabulary:
it is quite common to point to classes from well-known vocabularies.


=== OWL

Web Ontology Language (OWL) is much more complex

Yes, the abbreviation should have been `WOL`, but `OWL` sounds so much better... 

=== Reasoning

 If it looks like a duck, swims like a duck, and quacks like a duck, then it probably is a duck.

Vocabularies and ontologies do not magically turn RDF data into vast pools of knowledge.
It requires special tools, _reasoners_, to make assumptions and derive new facts
from the RDFS / OWL

== Validation

While reasoners can be used to detect some inconsistencies in data, 
they don't quite fit the bill as a general data quality tool.

Even worse, reasoners can derive new statements and may come to logical but surprising results, 
which is typically not the intended behavior when performing low-level quality checks.

For instance, if an ontology specifies that a person can only live in 1 place at the same time,
and we throw the statements `Jane lives in Paris` and `Jane lives in London` into the mix,
a reasoner may conclude that `Paris` and `London` are actually the same place...

=== SHACL

Validation is relative new



=== File formats

RDF data can be _serialized_ to several file formats

This may come in handy when dealing with 

Let's compare a few common file formats using following set of statements

.Set of statements
====
....
<vCard> <is a> <Standard>
<vCard> <has label> "Ontology for vCard"@en 
<vCard> <is published on> "22 May 2014"
....
====

==== N-Triples

This is a very simple text format, with every line containing one unabbreviated statement.
It can easily be streamed, and works quite nice with well-know command-line tools like `grep` and `awk`.

The downside is that N-Triples files are quite verbose,
since the format does not allow the use of prefixes to abbreviate commonly used namespaces,
nor does it provide options to group or structure statements in a visually appealing way ("pretty-printing").

.N-Triples file
====
....
<http://www.w3.org/2006/vcard/ns#> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://purl.org/dc/terms/Standard> .
<http://www.w3.org/2006/vcard/ns#> <http://www.w3.org/1999/02/22-rdf-syntax-ns#label> "Ontology for vCard"@en .
<http://www.w3.org/2006/vcard/ns#> <http://purl.org/dc/terms/issued> "2014-05-14"^^<http://www.w3.org/2001/XMLSchema#date> .
....
====

==== Turtle

Turtle is a slightly more complicated format, but is much more compact and easier to read.
Namespace prefixes can be used, and some syntactic sugar is available to produce smaller and better looking files.

It is therefore often used for files that are likely to be viewed by subject experts, e.g. data models and thesauri.

The following example shows how the statements can be (but don't have to be) nicely grouped together,
how namespaces prefixes can be used as a shorthand, 

Since the rdf:type, the `a` is a 

.Turtle file
====
....
@prefix dct: <http://purl.org/dc/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://www.w3.org/2006/vcard/ns#>:
  a dct:Standard ;
  rdf:label "Ontology for vCard"@en ;
  dct:issued "2014-05-14"^^xsd:date .
....
====


==== RDF/XML

RDF/XML was one of the first serialization formats, which is not

The format is quite generic and flexible, which also means that - even for small amounts of data - 
there are multiple ways to express the same data.

As with general XML, whitespace and indentation does not matter

.RDF/XML file
====
....
<?xml version="1.0" encoding="utf-8" ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:dct="http://purl.org/dc/terms/">

  <dct:Standard rdf:about="http://www.w3.org/2006/vcard/ns#">
    <rdf:label xml:lang="en">Ontology for vCard</rdf:label>
    <dct:issued rdf:datatype="http://www.w3.org/2001/XMLSchema#date">2014-05-14</dct:issued>
  </dct:Standard>

</rdf:RDF>
....
====


==== JSON-LD

=== Embedding in webpages

==== RDFa

It is, however, becoming a less popular solution.

==== JSON-LD in HTML

Search engines like Google benefit from structured data, and can use some 

See https://developers.google.com/search/docs/appearance/structured-data/dataset

=== Triple stores

RDF statements are often stored in specialized data stores, called _triple stores_.

Most of these triple stores offer import/export from multiple file formats,
and create/read/update/delete operations via the SPARQL query and update language.

It is, however, not always necessary to use a triple store to generate RDF data.
Sometimes a database and a template engine will do just fine.


= Data Catalog (DCAT)

== DCAT

Is a very simple, based on <<DCTERMS>>


[plantuml]
....
title simplified model

Catalog - Dataset 
Dataset - Distribution

....

=== DCAT 2

DCAT version 2 adds better support for (web)services

=== DCAT 3

DCAT version 3 focusses on documenting series of related datasets.

It is up to the publishere of the datasets to decide what "related" means: 
it could be a collection of statistics published throughout the years, for instance, 
or a set of road maps, ...


== DCAT-AP


See also https://semiceu.github.io/DCAT-AP/releases/3.0.0/


=== Catalog

==== Describing the catalog



=== Dataset

==== Describing the dataset

`dct:title`

`dct:description`

`dcat:keyword`
`dcat:theme`

==== Licenses and rights


=== Distribution

==== Accessing and downloading

`dcat:accessURL`
`dcat:downloadURL`

=== Dataservice



== Various specializations

=== BRegDCAT-AP


See also https://github.com/SEMICeu/BregDCAT-AP

=== CiteDCAT-AP

See also https://ec-jrc.github.io/datacite-to-dcat-ap/

=== DCAT-AP-JRC

See also https://ec-jrc.github.io/dcat-ap-jrc/

=== DCAT-AP HvD
Implementing Regulation 2023/138/EU of 21 December 2022 laying down a list of specific high-value datasets and the arrangements for their publication and re-use

See also https://semiceu.github.io/DCAT-AP/releases/2.2.0-hvd/

=== EPOS-DCAT-AP

See also https://epos-eu.github.io/EPOS-DCAT-AP/

=== GeoDCAT-AP
Directive 2007/2/EC of 14 March 2007 establishing an Infrastructure for Spatial Information in the European Community (INSPIRE)

https://semiceu.github.io/GeoDCAT-AP/releases/

=== GNSS-DCAT-AP

See also https://zenodo.org/records/10955559

=== HealthDCAT-AP

See also https://healthdcat-ap.github.io/

=== MLDCAT-AP

See also https://semiceu.github.io/MLDCAT-AP/releases/2.0.0/

=== MobilityDCAT-AP
Directive 2010/40/EU of 7 July 2010 on the framework for the deployment of 
Intelligent Transport Systems in the field of road transport and for interfaces with other modes of transport (ITS)

See also https://w3id.org/mobilitydcat-ap/releases/

=== StatDCAT-AP

See also https://github.com/SEMICeu/StatDCAT-AP

== National variants

=== Belgium
DCAT-AP-BE
DCAT-AP-VL

=== Finland
https://www.avoindata.fi/en/dcat-ap

=== Germany
DCAT-AP.DE

=== Italy: DCAT-AP_IT
https://www.dati.gov.it/content/dcat-ap-it-v10-profilo-italiano-dcat-ap-0

=== The Netherlands: DCAT-AP-DONL
https://dataoverheid.github.io/dcat-ap-donl/

=== Norway: DCAT-AP-NO
https://data.norge.no/specification/dcat-ap-no

=== Poland: DCAT-AP-PL
https://dane.gov.pl/dcat-ap-pl/

=== Spain: DCAT-AP-Spain

=== Sweden: DCAT-AP-SE
https://docs.dataportal.se/dcat/en/

=== Switserland: DCAT-AP CH
https://www.dcat-ap.ch/

= Vocabularies

The following section provides an overview of vocabularies that are commonly used with,
or referred to by, DCAT-AP.

Once again the aim is not to be complete,
but to give a practical overview of the most important classes and properties within the context of data catalogs.

== ADMS

== DCTERMS

[cols="1h,1"]
|===
|Full name | Dublin Core Metadata Initiative Terms
|See also | https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
|Classes | FileFormat, Frequency, LicenseDocument, LinguisticSystem, Location, 
            MediaType, MediaTypeOrExtent, PeriodOfTime, ProvenanceStatement, 
            RightsStatement, Standard
|Properties | accessRights, accrualPeriodicity, available, conformsTo, contributor, 
            created, creator, description, format, identifier, issued, language, 
            license, modified, provenance, publisher, references, relation, rights, 
            rightsHolder, source, spatial, subject, title, type
|===


Most people will associate Dublin with the capital of Ireland, 
but in this case it refers to Dublin in Ohio, USA.

== DQV

[cols="1h,1"]
|===
|Full name | Data Quality Vocabulary
|See also | https://www.w3.org/TR/vocab-dqv/
|===


== FOAF

[cols="1h,1"]
|===
|Full name | Friend-of-a-Friend
|Namespace | http://xmlns.com/foaf/0.1/
|See also | http://xmlns.com/foaf/spec/
|Classes | Agent, Document, Organization, Person
|Properties | familyName, givenName, homepage, name, page, primaryTopic
|===


A `Person` or an `Organization`, acting an an `Agent`
`

== LOCN

[cols="1h,1"]
|===
|Full name | Location Core Vocabulary
|Namespace | http://www.w3.org/ns/locn#
|See also | https://www.w3.org/ns/legacy_locn
|Classes | 
|Properties |
|===

Physical location

A newer version is being developed under the SEMIC.eu umbrella as the
https://semiceu.github.io/Core-Location-Vocabulary/[Core Location Vocabulary]

== ORG


== OWL

[cols="1h,1"]
|===
|Full name | Web Ontology Language
|Namespace | http://www.w3.org/2002/07/owl#
|See also | https://www.w3.org/TR/owl2-rdf-based-semantics/
|Classes | 
|Properties | sameAs, versionInfo
|===

`owl:versionInfo' is sometimes used to add version information to Datasets


`owl:sameAs` is used to indicate that two subjects A and B are just two URIs describing the exact same thing.
This may have some unintended side-effects when a reasoner comes into play, 
because it implies that any statement about A is also a statement about B and vice versa,
so use with care.

An alternative approach is to use the `skos:exactMatch` property, 
which merely indicates that different subjects match, without affecting reasoning.


== PROV


== Schema

[cols="1h,1"]
|===
|Full name | Schema.org
|Namespace | https://schema.org/
|See also | https://schema.org
|Properties | endDate, startDate
|===

Schema.org is a massive collection of useful classes and properties.
Founded by search engins Google, Yahoo, (Microsoft) Bing and Yandex, it features an
interesting mix of e-commerce, health and

DCAT originally used `schema:startDate` and `schema:endDate` to indicate the temporal coverage of a dataset,
but DCAT version 2 added two very similar properties `dcat:startDate`and `dcat:endDate`.

See https://github.com/w3c/dxwg/issues/85 for an in-depth discussion on why these properties were duplicated.

Most readers only need to remember that the `dcat:`-versions are now the preferred way to document start and end date.

== SKOS

[cols="1h,1"]
|===
|Full name | Simple Knowledge Organization System
|Namespace | http://www.w3.org/2004/02/skos/core#
|See also | https://www.w3.org/TR/skos-reference/
|Classes | Concept, ConceptScheme
|Properties | altLabel, broader, hasTopConcept, inScheme, narrower, notation, 
            prefLabel, sameAs, topConceptOf
|===

It is very well suited to publish code lists and 

A _term_ (entry in a thesauri) 
`skos:Concept`

The `skos:broader` (and the inverse property `skos:narrower`) is used to create hierachical structures.

=== Labels

Every term should have a preferred label `skos:prefLabel` (possibly in multiple languages), 
and may have multiple alternative labels `skos:altLabel` 

In addition - or instead of a - prefLabel

=== Mapping to other thesauri

It is also possible to compare terms in one thesaurus with terms belonging to another thesaurus,
using the `skos:broadMatch`, `skos:narrowMatch`, `skos:closeMatch` and `skos:exactMatch` properties.


The EU Publications Office publishes various code lists and thesauri in SKOS,
ranging from simple lists like the https://op.europa.eu/en/web/eu-vocabularies/authority-tables[Authority tables]
to massive thesauri like https://op.europa.eu/en/web/eu-vocabularies/thesauri[EUROVOC]

== VCARD

[cols="1h,1"]
|===
|Full name | vCard Ontology
|Namespace | http://www.w3.org/2006/vcard/ns#
|See also | https://www.w3.org/TR/vcard-rdf/
|Classes | Individual, Kind, Organization
|Properties | fn, hasEmail
|===

Is a bit...messy. 


== XSD

[cols="1h,1"]
|===
|Full name | XML Schema Part 2: Datatypes
|Namespace | http://www.w3.org/2001/XMLSchema#
|See also | http://www.w3.org/TR/xmlschema-2/
|Classes | Individual, Kind, Organization
|Properties | fn, hasEmail
|===


[appendix]
= Lists of identifiers

=== Persons

It is sometimes useful to add metadata about individuals to datasets.
Researchers, for instance, often want to be mentioned as the author of - or a contributor to - a dataset or scientific paper.

Unfortunately names are unlikely to be unique - just imagine how many `John Smith`'s there are -
so it's not always possible to 


=== Organizations


Opencorporates.org

=== File formats

DCAT-AP requires the use of the Publication Office's 
https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/file-type[File type autority table] 
for `dct:format` URIs

However, the dcat properties `dcat:mediaType`, `dcat:compressFormat`, `dcat:packageFormat` should all be using URIS of registered IANA mimetypes.

Note that there isn't always a registered IANA mimetype when there is an entry in the Publication Offices's authority table, or vice versa.

In general, the Publication Office is quite flexible in adding new file formats.
Everyone can make suggestions via the `Contribut`] button on the
https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://publications.europa.eu/resource/authority/file-type[File type overview page].

IANA procedures are a bit more strict, especially when it comes down to registering vendor-specific formats,
but they too offer a https://www.iana.org/form/media-types[webform] to submit suggestions.

=== Geographic areas

Geonames.org

[appendix]
= Common mistakes in DCAT-AP


=== Not using the EU Publications Office controlled lists

Some portals claim to adhere to DCAT-AP, but are in fact producing DCAT.

=== Incorrect date or duration formats


=== Mixing contact point IDs and organization IDs

=== Mixing IDs and URLs

This can lead to undesired side-effects when quering / combining data.


=== Not setting explicit language tags

[appendix]
= Tools

== 

To find the preferred prefix and/or namespaces: https://prefix.cc/

==

[index]
== Index

