= Introduction to DCAT-AP
Bart Hanssens
v1.0
:doctype: docbook
:toc: left

= Introduction to linked data

== Problem statement 

So to sum up, we want

* unique, easy to generate identifiers
* easy to find documentation


== Introduction to linked data

Resource Description Framework

=== Statements and triples ===

RDF is about making _statements_, which are basic sentences to describe something.
written down as a combination 3 parts (hence the name _triples_).

`<subject> <predicate> <object>`

Statements are just that, they are not guaranteed to be true, and anyone can make any statement on whatever topic.

WHich is, of course, just like the human-friendly World Wide Web works: 
anyone can create webpages and link to other pages, because that's the whole point of the WWW in the first place...

=== Unique identifiers

One way to make sure identifiers are unique, is to use a common database or registration system.

Luckily there is a decentralized solution, based on domain names.


==== URI and URLs


[NOTE]
====
`http://example.com` and `https://example.com` are *not* assumed to be the same identifier.
====

==== Dereferencable URLs

Dereferencable is a fancy word to say that a URL will actually return something meaningful when a browser 
or another tool wants to check it out.

[NOTE]
====
A URL does not _have_ to be dereferencable in order to be used as an identifier, but it helps.
====

==== Persistent URLs (PURL)

A persistent URL (or PURL in short) is nothing more (and nothing less) than an URL that does not change.
For how long ? Basically forever... once a PURL has been created, it is supposed to remain available and 
unchanged until eternity.

=== File formats

Data contained in RDF can be _serialized_ to several file formats

This may come in handy when dealing with 

There is, however 

==== N-Triples

This is a very simple text format, with every line containing one unabbreviated statement.
It can easily be streamed, and works quite nice with well-know command-line tools like `grep` and `awk`.
The downside is that N-Tripes is quite verbose,
since the format does not allow the use of prefixes to abbreviate commonly used namespaces,
nor does it provide options to group or structure statements in a visually appealing way ("pretty-printing").

==== Turtle

Turtle is slightly more complicated, but can be much more compact and easier to read.
Prefixes can be used, and some syntactic sugar is available to produce smaller and better looking files.
It is therefore often used for files that are likely to be viewed by data experts, like data models and thesauri.

==== RDF/XML

RDF/XML was one of the first serialization formats, which is not

==== JSON-LD

=== Embedding in webpages

==== RDFa

It is, however, becoming a less popular solution.

==== JSON-LD in HTML

Search engines like Google 

== Modelling

=== RDFS
=== OWL

== Validating

=== SHACL

= Data catalogs

== Data Catalog (DCAT)
=== DCAT

=== DCAT 2

=== DCAT 3

== DCAT-AP

== Various specializations

=== BRegDCAT-AP

=== DCAT-AP-JRC

=== DCAT-AP HvD
Implementing Regulation 2023/138/EU of 21 December 2022 laying down a list of specific high-value datasets and the arrangements for their publication and re-use

=== GeoDCAT-AP
Directive 2007/2/EC of 14 March 2007 establishing an Infrastructure for Spatial Information in the European Community (INSPIRE)

=== HealthDCAT-AP

=== MLDCAT-AP

=== MobilityDCAT-AP
Directive 2010/40/EU of 7 July 2010 on the framework for the deployment of Intelligent Transport Systems in the field of road transport and for interfaces with other modes of transport (ITS)

=== StatDCAT-AP

.DRAFT
----
This document is only a rough draft.
----
